// build-index.js
// Scans first level folders and builds index.json with image metadata.
// Updated to include thumbnailPath for each image.

const fs = require("fs");
const path = require("path");

const ROOT_DIR = __dirname;
const OUTPUT_FILE = path.join(ROOT_DIR, "index.json");
const IMAGE_EXTENSIONS = new Set([".png", ".jpg", ".jpeg", ".webp"]);
const SKIP_DIRS = new Set([".git", ".github", "node_modules", "thumbnails"]);

function isImageFile(fileName) {
  return IMAGE_EXTENSIONS.has(path.extname(fileName).toLowerCase());
}

function getCategories(rootDir) {
  return fs
    .readdirSync(rootDir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !SKIP_DIRS.has(e.name))
    .map((e) => e.name);
}

function getImagesForCategory(rootDir, categoryName) {
  const categoryPath = path.join(rootDir, categoryName);
  const images = [];

  for (const entry of fs.readdirSync(categoryPath, { withFileTypes: true })) {
    if (!entry.isFile() || !isImageFile(entry.name)) continue;

    const fileName = entry.name;
    const relativePath = `${categoryName}/${fileName}`;
    // thumbnailPath points to the WebP thumbnail generated by generate-thumbnails.js
    const thumbnailPath = `thumbnails/${categoryName}/${path.parse(fileName).name}.webp`;

    images.push({ path: relativePath, fileName, thumbnailPath });
  }

  return images;
}

function buildIndex() {
  const categories = getCategories(ROOT_DIR);
  const result = {
    generatedAt: new Date().toISOString(),
    categories: [],
  };

  for (const categoryName of categories) {
    const images = getImagesForCategory(ROOT_DIR, categoryName);
    if (images.length === 0) continue;
    result.categories.push({ id: categoryName, name: categoryName, images });
  }

  return result;
}

function main() {
  const index = buildIndex();
  fs.writeFileSync(OUTPUT_FILE, JSON.stringify(index, null, 2), "utf8");

  const totalImages = index.categories.reduce(
    (sum, cat) => sum + cat.images.length,
    0
  );

  console.log(
    `index.json written — ${index.categories.length} categories, ${totalImages} images`
  );
}

main();
